<?php
if (!defined('ABSPATH')) { exit; }

function kcj_content_tropes() {
    return [
        [
            'slug' => 'enemies-to-lovers',
            'title' => 'Enemies to Lovers',
            'one' => 'Two people who start as friction and end as gravity.',
            'craft' => 'Rivalry stores energy. Every insult is unfinished dialogue. When status or duty finally bends, the release feels earned.',
            'soft' => 'Soft reading: hostility was armor. Softening is courage.',
            'mirror' => 'Mirror reading: bickering is just foreplay with better lighting.',
            'k' => 'K: workplace rivals, chaebol vs idealist.',
            'c' => 'C: rival sects, court factions, face-slap prelude to soft eyes.',
            'j' => 'J: polite distance that reads as dislike until it isn’t.',
        ],
        [
            'slug' => 'contract-marriage',
            'title' => 'Contract Marriage',
            'one' => 'A paperwork relationship that refuses to stay paperwork.',
            'craft' => 'Rules create a safe stage for intimacy to sneak in. Clauses are comic — until someone breaks them for love.',
            'soft' => 'Soft: choosing each other after the contract expires is the real vow.',
            'mirror' => 'Mirror: Clause 7 said no feelings. Clause 7 was a clown.',
            'k' => 'K: inheritance, visa-adjacent pressure, family boardrooms.',
            'c' => 'C: political marriage plots in costume arcs.',
            'j' => 'J: quieter practical arrangements, shame vs tenderness.',
        ],
        [
            'slug' => 'fake-dating',
            'title' => 'Fake Dating',
            'one' => 'Pretend couple energy that accidentally becomes real.',
            'craft' => 'Performance forces proximity; proximity forces truth.',
            'soft' => 'Soft: the audience inside the story is the cold world; the warm world is private.',
            'mirror' => 'Mirror: practice kissing schedules are a crime against emotional neutrality.',
            'k' => 'K: PR couples, family events.',
            'c' => 'C: disguise arcs in modern and fantasy.',
            'j' => 'J: workplace cover stories.',
        ],
        [
            'slug' => 'second-lead-magnetic',
            'title' => 'Second Lead Magnetic',
            'one' => 'The supporting love interest who feels like the secret main.',
            'craft' => 'Structural kindness + timing = audience mutiny.',
            'soft' => 'Soft: longing that stays gentle still matters.',
            'mirror' => 'Mirror: welcome to the shrine. Bring tissues and bad takes.',
            'k' => 'K: classic SLS culture.',
            'c' => 'C: loyal general / childhood ally variants.',
            'j' => 'J: quiet senpai who deserved better.',
        ],
        [
            'slug' => 'selective-amnesia',
            'title' => 'Selective Amnesia',
            'one' => 'Memory loss used as a romance reset button.',
            'craft' => 'It tests care without shared history — love as verb, not souvenir.',
            'soft' => 'Soft: choosing someone again is a second first love.',
            'mirror' => 'Mirror: convenient amnesia has a union and a dental plan.',
            'k' => 'K: accident + hospital arcs.',
            'c' => 'C: curse / reincarnation adjacent wipes.',
            'j' => 'J: softer psychological blanks.',
        ],
        [
            'slug' => 'rain-confession',
            'title' => 'Rain Confession',
            'one' => 'Weather as emotional amplifier.',
            'craft' => 'Rain removes social polish; wet hair equals honesty DLC.',
            'soft' => 'Soft: the world shrinks to two people and weather.',
            'mirror' => 'Mirror: umbrella scarcity is the national sport.',
            'k' => 'K: iconic visual lexicon.',
            'c' => 'C: courtyard downpours in costume.',
            'j' => 'J: silent shared umbrella walks.',
        ],
        [
            'slug' => 'piggyback-escape',
            'title' => 'Piggyback Escape',
            'one' => 'Carrying someone through chaos as intimacy shorthand.',
            'craft' => 'Care becomes physical choreography — trust you can feel in your knees.',
            'soft' => 'Soft: being held is the confession before words.',
            'mirror' => 'Mirror: ankles were invented for this plot.',
            'k' => 'K: near-miss traffic energy.',
            'c' => 'C: night flight through alleys / sect grounds.',
            'j' => 'J: festival crowds, missed last train.',
        ],
        [
            'slug' => 'wrist-grab-halt',
            'title' => 'Wrist-Grab Halt',
            'one' => 'The mid-stride grab that stops a goodbye.',
            'craft' => 'Interruption is desire with bad manners and perfect timing.',
            'soft' => 'Soft: please don’t leave is a full sentence.',
            'mirror' => 'Mirror: wrists have more screen time than some supporting casts.',
            'k' => 'K: hallway / street classic.',
            'c' => 'C: sleeve-pull hanfu variant.',
            'j' => 'J: sleeve tug, then silence.',
        ],
        [
            'slug' => 'chaebol-inheritance',
            'title' => 'Chaebol Inheritance War',
            'one' => 'Money family politics as romance obstacle course.',
            'craft' => 'Power makes affection dangerous; choosing love costs status.',
            'soft' => 'Soft: the heir who wants a normal morning coffee.',
            'mirror' => 'Mirror: desk slam, stock ticker, secret twin optional.',
            'k' => 'K: home turf.',
            'c' => 'C: business empire modern dramas.',
            'j' => 'J: konglomerat-lite family firms.',
        ],
        [
            'slug' => 'noona-soft-power',
            'title' => 'Noona Soft Power',
            'one' => 'Older-woman / younger-man tenderness without apology.',
            'craft' => 'Competence meets earnestness; age is texture, not punchline.',
            'soft' => 'Soft: caretaking that goes both ways.',
            'mirror' => 'Mirror: ‘sunbae please’ industrial complex.',
            'k' => 'K: signature comfort zone.',
            'c' => 'C: less branded, still present in modern arcs.',
            'j' => 'J: office age-gap restraint.',
        ],
        [
            'slug' => 'workplace-hierarchy',
            'title' => 'Workplace Hierarchy Romance',
            'one' => 'Love climbing the org chart carefully.',
            'craft' => 'Power imbalance is the conflict engine; ethics is the test.',
            'soft' => 'Soft: respect is the love language.',
            'mirror' => 'Mirror: overtime is just extended eye contact.',
            'k' => 'K: office rom-coms.',
            'c' => 'C: corporate modern.',
            'j' => 'J: shokuba dorama specialty.',
        ],
        [
            'slug' => 'evil-inlaw-raid',
            'title' => 'Evil In-Law Raid',
            'one' => 'Family veto as final boss.',
            'craft' => 'Belonging vs blood loyalty — romance must negotiate a tribe.',
            'soft' => 'Soft: chosen family eventually speaks up.',
            'mirror' => 'Mirror: mother-in-law has a raid mechanic.',
            'k' => 'K: makjang fuel.',
            'c' => 'C: clan elders.',
            'j' => 'J: quiet disapproval that still cuts.',
        ],
        [
            'slug' => 'childhood-friend-stall',
            'title' => 'Childhood Friend Stall',
            'one' => 'History without confession — until a rival arrives.',
            'craft' => 'Familiarity hides desire; threat reveals it.',
            'soft' => 'Soft: the person who knew your unfinished sentences.',
            'mirror' => 'Mirror: childhood friend buff, final boss luck: terrible.',
            'k' => 'K: used, but less meme-law than JP media.',
            'c' => 'C: betrothal-from-childhood variants.',
            'j' => 'J: culturally loud trope / meme.',
        ],
        [
            'slug' => 'time-limit-love',
            'title' => 'Time-Limit Love',
            'one' => 'A deadline that forces honesty.',
            'craft' => 'Mortality or departure compresses politeness into truth.',
            'soft' => 'Soft: every ordinary day becomes sacred.',
            'mirror' => 'Mirror: calendar apps as villains.',
            'k' => 'K: illness / departure arcs.',
            'c' => 'C: cultivation tribulation clocks.',
            'j' => 'J: transfer / last episode confessions.',
        ],
        [
            'slug' => 'hidden-identity',
            'title' => 'Hidden Identity Softens',
            'one' => 'Masks, aliases, bodyguards — love sees through costume.',
            'craft' => 'Recognition scenes pay off long attention.',
            'soft' => 'Soft: being known is the gift.',
            'mirror' => 'Mirror: glasses = invisible, somehow.',
            'k' => 'K: heir undercover.',
            'c' => 'C: prince in disguise energy.',
            'j' => 'J: softer secret-life plots.',
        ],
        [
            'slug' => 'idol-civilian',
            'title' => 'Idol–Civilian Gravity',
            'one' => 'Fame vs ordinary mornings.',
            'craft' => 'Privacy becomes the romantic prize.',
            'soft' => 'Soft: love as shelter from the crowd.',
            'mirror' => 'Mirror: disguise hats do nothing and we love them.',
            'k' => 'K: strong lane.',
            'c' => 'C: entertainment industry modern.',
            'j' => 'J: less dominant but present.',
        ],
        [
            'slug' => 'transmigration-book',
            'title' => 'Transmigration Into the Book',
            'one' => 'Wake up inside the story you judged.',
            'craft' => 'Meta-agency: rewrite fate with future knowledge — and new feelings.',
            'soft' => 'Soft: empathy for the ‘villain’ you once booed.',
            'mirror' => 'Mirror: save-scumming the romance route.',
            'k' => 'K: rarer.',
            'c' => 'C: huge web-novel → drama engine.',
            'j' => 'J: isekai-adjacent lighter TV.',
        ],
        [
            'slug' => 'face-slap-court',
            'title' => 'Face-Slapping Court Arc',
            'one' => 'Public humiliate-the-bully payoffs.',
            'craft' => 'Justice fantasy braided with romance status.',
            'soft' => 'Soft: dignity restored, then gentleness.',
            'mirror' => 'Mirror: slap counter goes brrr.',
            'k' => 'K: chaebol press-conference vibes.',
            'c' => 'C: signature xianxia/modern revenge romance.',
            'j' => 'J: rarer; shame works quieter.',
        ],
        [
            'slug' => 'red-thread-destiny',
            'title' => 'Red-Thread Destiny',
            'one' => 'Fate as a soft rope between two people.',
            'craft' => 'Predestination vs choice — romance argues both.',
            'soft' => 'Soft: recognition across lifetimes.',
            'mirror' => 'Mirror: fate has a string budget.',
            'k' => 'K: ‘destined’ marketing language.',
            'c' => 'C: literal mythic imagery common.',
            'j' => 'J: en / red string folklore echoes.',
        ],
        [
            'slug' => 'palace-scheme-couple',
            'title' => 'Palace Scheme Couple',
            'one' => 'Love under surveillance and succession math.',
            'craft' => 'Intimacy is resistance inside ritual.',
            'soft' => 'Soft: a glance that is also a strategy.',
            'mirror' => 'Mirror: poisoned tea tasting menu.',
            'k' => 'K: sageuk.',
            'c' => 'C: palace / historical romance engine.',
            'j' => 'J: jidaigeki-adjacent rarer on mainstream TV.',
        ],
        [
            'slug' => 'slow-burn-silence',
            'title' => 'Slow-Burn Silence',
            'one' => 'Almost-touching as the whole plot.',
            'craft' => 'Restraint stores voltage; small gestures become earthquakes.',
            'soft' => 'Soft: the courage of a single honest sentence.',
            'mirror' => 'Mirror: 10 episodes of vibes, 1 confession, still perfect.',
            'k' => 'K: exists inside louder frames.',
            'c' => 'C: long novel pacing.',
            'j' => 'J: specialty of the house.',
        ],
        [
            'slug' => 'last-episode-confess',
            'title' => 'Last-Episode Confession',
            'one' => 'Saving the words for the door.',
            'craft' => 'Delay is structure — catharsis needs scarcity.',
            'soft' => 'Soft: timing as tenderness.',
            'mirror' => 'Mirror: calendars fear finale night.',
            'k' => 'K: common pressure cooker.',
            'c' => 'C: finale banquet reveals.',
            'j' => 'J: extremely on-brand.',
        ],
        [
            'slug' => 'drunk-truth',
            'title' => 'Drunk Truth',
            'one' => 'Alcohol as truth serum lighting cue.',
            'craft' => 'Inhibition drops; affection trips into the open.',
            'soft' => 'Soft: the heart practiced the speech sober.',
            'mirror' => 'Mirror: soju produced by the plot department.',
            'k' => 'K: classic.',
            'c' => 'C: banquet wine.',
            'j' => 'J: afterwork nomikai soft chaos.',
        ],
        [
            'slug' => 'hospital-vigil',
            'title' => 'Hospital Vigil',
            'one' => 'Care beside a bed as devotion proof.',
            'craft' => 'Service replaces speeches.',
            'soft' => 'Soft: love as staying.',
            'mirror' => 'Mirror: heart monitors keep better rhythm than some OST drops.',
            'k' => 'K: frequent.',
            'c' => 'C: injury after duel / accident.',
            'j' => 'J: quieter sickbed arcs.',
        ],
        [
            'slug' => 'meet-cute-collision',
            'title' => 'Meet-Cute Collision',
            'one' => 'Bodies bump, coffee spills, destiny files a report.',
            'craft' => 'Accident creates owed attention.',
            'soft' => 'Soft: embarrassment as icebreaker.',
            'mirror' => 'Mirror: physics engines hate leads.',
            'k' => 'K: street / office door.',
            'c' => 'C: rooftop / market crowd.',
            'j' => 'J: train platform.',
        ],
        [
            'slug' => 'umbrella-economy',
            'title' => 'Umbrella Economy',
            'one' => 'One umbrella, two people, zero chill.',
            'craft' => 'Shared shelter = forced intimacy geometry.',
            'soft' => 'Soft: choosing to get a little wet together.',
            'mirror' => 'Mirror: umbrella inflation is romance GDP.',
            'k' => 'K: staple.',
            'c' => 'C: oil-paper umbrella aesthetic.',
            'j' => 'J: rainy season soft power.',
        ],
        [
            'slug' => 'car-confession-chase',
            'title' => 'Car Confession Chase',
            'one' => 'Vehicles, U-turns, roadside honesty.',
            'craft' => 'Motion externalizes emotional U-turns.',
            'soft' => 'Soft: stopping the car is starting the life.',
            'mirror' => 'Mirror: 180° turn cinematic universe.',
            'k' => 'K: meme-tier famous.',
            'c' => 'C: less car-mythic, more horse/carriage in costume.',
            'j' => 'J: quieter taxi talks.',
        ],
        [
            'slug' => 'found-family-crew',
            'title' => 'Found Family Crew',
            'one' => 'The romance sits inside a friend constellation.',
            'craft' => 'Side characters prove the lead can love at all.',
            'soft' => 'Soft: belonging multiplies courage.',
            'mirror' => 'Mirror: the squad knows before they do.',
            'k' => 'K: strong friend group comedies.',
            'c' => 'C: sect found family.',
            'j' => 'J: workplace found family.',
        ],
        [
            'slug' => 'rival-companies',
            'title' => 'Rival Companies Merge',
            'one' => 'Love across brand war.',
            'craft' => 'Market conflict mirrors heart conflict.',
            'soft' => 'Soft: collaboration as metaphor.',
            'mirror' => 'Mirror: hostile takeover of feelings.',
            'k' => 'K: chaebol vs chaebol.',
            'c' => 'C: corporate modern.',
            'j' => 'J: department rivalry.',
        ],
        [
            'slug' => 'spy-softens',
            'title' => 'Spy Softens',
            'one' => 'Mission vs affection.',
            'craft' => 'Double life forces a choice of truth.',
            'soft' => 'Soft: disarmament as romance.',
            'mirror' => 'Mirror: ‘I was assigned to watch you’ starter pack.',
            'k' => 'K: action-romance hybrids.',
            'c' => 'C: historical agent arcs.',
            'j' => 'J: rarer thriller-romance.',
        ],
        [
            'slug' => 'food-as-love',
            'title' => 'Food as Love Language',
            'one' => 'Cooking, feeding, leftover care.',
            'craft' => 'Nurture made edible.',
            'soft' => 'Soft: a meal is a promise.',
            'mirror' => 'Mirror: bento espionage.',
            'k' => 'K: ramyeon 2AM.',
            'c' => 'C: banquet + humble noodle equality.',
            'j' => 'J: homemade excellence.',
        ],
        [
            'slug' => 'letter-never-sent',
            'title' => 'Letter Never Sent',
            'one' => 'Unsent words as tension vault.',
            'craft' => 'Writing practices courage the mouth hasn’t learned.',
            'soft' => 'Soft: finding the letter is mutual recognition.',
            'mirror' => 'Mirror: postal service of doom.',
            'k' => 'K: diary / note tropes.',
            'c' => 'C: poetry exchanges.',
            'j' => 'J: handwritten restraint.',
        ],
        [
            'slug' => 'parallel-timelines',
            'title' => 'Parallel Timelines',
            'one' => 'Other versions of us.',
            'craft' => 'Choice becomes visible by contrast.',
            'soft' => 'Soft: this timeline’s ordinary love is the miracle.',
            'mirror' => 'Mirror: multiverse but make it sobbing.',
            'k' => 'K: fantasy romances.',
            'c' => 'C: rebirth loops.',
            'j' => 'J: literary what-ifs.',
        ],
        [
            'slug' => 'villainess-rewrite',
            'title' => 'Villainess Rewrites Fate',
            'one' => 'Labeled villain chooses a kinder plot.',
            'craft' => 'Agency + redemption + romance literacy.',
            'soft' => 'Soft: rewriting cruelty into care.',
            'mirror' => 'Mirror: speedrun: avoid death flag, collect love interest.',
            'k' => 'K: limited.',
            'c' => 'C: massive web-novel mood.',
            'j' => 'J: otome-game parody adjacent.',
        ],
        [
            'slug' => 'office-senpai-distance',
            'title' => 'Office Senpai Distance',
            'one' => 'Ranked politeness as slow heat.',
            'craft' => 'Keigo and hierarchy delay confession — deliciously.',
            'soft' => 'Soft: equality arrives as the love climax.',
            'mirror' => 'Mirror: name-code switching is the kiss.',
            'k' => 'K: sunbae culture.',
            'c' => 'C: manager / junior.',
            'j' => 'J: peak form.',
        ],
        [
            'slug' => 'ost-bond',
            'title' => 'OST as Emotional Architecture',
            'one' => 'Music teaches the audience how to feel before dialogue does.',
            'craft' => 'Leitmotifs train memory; reunion tracks unlock tears.',
            'soft' => 'Soft: the song is a shared private room.',
            'mirror' => 'Mirror: one piano line and suddenly you’re unpaid emotional labor.',
            'k' => 'K: industrial strength.',
            'c' => 'C: theme songs as branding.',
            'j' => 'J: softer insert songs.',
        ],
        [
            'slug' => 'memory-promise',
            'title' => 'Memory of a Promise',
            'one' => 'A childhood pact returns as adult plot.',
            'craft' => 'Time proves sincerity.',
            'soft' => 'Soft: keeping a foolish promise is wisdom.',
            'mirror' => 'Mirror: pinky swears have legal power in dramaland.',
            'k' => 'K: common.',
            'c' => 'C: reincarnation promise variants.',
            'j' => 'J: childhood vow memes.',
        ],
        [
            'slug' => 'dream-shared',
            'title' => 'Dream-Shared Nights',
            'one' => 'Shared dreams as intimacy without touch.',
            'craft' => 'Subconscious becomes the honest set.',
            'soft' => 'Soft: meeting where fear can’t pose.',
            'mirror' => 'Mirror: dream logic continuity errors, still cute.',
            'k' => 'K: fantasy romances.',
            'c' => 'C: cultivation dream realms.',
            'j' => 'J: surreal late-night TV.',
        ],
        [
            'slug' => 'bodyguard-orbit',
            'title' => 'Bodyguard Orbit',
            'one' => 'Protection as proximity engine.',
            'craft' => 'Duty is the excuse; devotion is the leak.',
            'soft' => 'Soft: safety becomes home.',
            'mirror' => 'Mirror: ‘stay behind me’ industrial complex.',
            'k' => 'K: chaebol security.',
            'c' => 'C: shadow guard classics.',
            'j' => 'J: less common.',
        ],
        [
            'slug' => 'class-gap-tender',
            'title' => 'Class-Gap Tenderness',
            'one' => 'Wealth and ordinary life learning each other’s mornings.',
            'craft' => 'Empathy across asymmetry without mocking either side.',
            'soft' => 'Soft: dignity is mutual.',
            'mirror' => 'Mirror: poor lead teaches rich lead groceries.',
            'k' => 'K: core fantasy.',
            'c' => 'C: urban / historical both.',
            'j' => 'J: understated economic gaps.',
        ],
    ];
}

function kcj_content_syndromes() {
    return [
        [
            'slug' => 'second-lead-syndrome',
            'title' => 'Second Lead Syndrome',
            'one' => 'You wanted the other person to win — and you’re not sorry.',
            'soft' => 'Soft: your heart votes for gentleness.',
            'mirror' => 'Mirror: build the shrine, ignore the finale committee.',
        ],
        [
            'slug' => 'amnesia-fatigue',
            'title' => 'Main Lead Amnesia Fatigue',
            'one' => 'You can predict the wipe before the ambulance arrives.',
            'soft' => 'Soft: still cry when care remains.',
            'mirror' => 'Mirror: memory cards sold separately.',
        ],
        [
            'slug' => 'ost-tear-reflex',
            'title' => 'OST Tear Reflex',
            'one' => 'Two piano notes and you’re compromised.',
            'soft' => 'Soft: music is honest.',
            'mirror' => 'Mirror: composers own your tear ducts.',
        ],
        [
            'slug' => 'ep12-betrayal',
            'title' => 'Episode-12 Betrayal Expectation',
            'one' => 'Midpoint chaos feels like destiny’s midterm exam.',
            'soft' => 'Soft: conflict proves stakes.',
            'mirror' => 'Mirror: calendar alerts labeled ‘emotional damage’.',
        ],
        [
            'slug' => 'just-one-more',
            'title' => 'I’ll Just Watch One',
            'one' => 'Lies we tell at 00:14.',
            'soft' => 'Soft: hunger for story is human.',
            'mirror' => 'Mirror: sleep is a western concept.',
        ],
        [
            'slug' => 'chaebol-hangover',
            'title' => 'Chaebol Unreality Hangover',
            'one' => 'Aftercare for leaving dramaland economics.',
            'soft' => 'Soft: keep the tenderness, return the penthouse.',
            'mirror' => 'Mirror: your boss is not going to U-turn for you.',
        ],
        [
            'slug' => 'face-slap-withdrawal',
            'title' => 'Face-Slap Withdrawal',
            'one' => 'When modern plots are too polite.',
            'soft' => 'Soft: seek dignity arcs elsewhere.',
            'mirror' => 'Mirror: slap detox smoothie.',
        ],
        [
            'slug' => 'childhood-friend-rage',
            'title' => 'Childhood Friend Rage',
            'one' => 'They waited, they lost, you’re furious.',
            'soft' => 'Soft: timing is a character flaw we all have.',
            'mirror' => 'Mirror: file a complaint with Fate HR.',
        ],
        [
            'slug' => 'slow-burn-starvation',
            'title' => 'Slow-Burn Starvation',
            'one' => 'Nine episodes of almost.',
            'soft' => 'Soft: patience is participation.',
            'mirror' => 'Mirror: throw a bread roll at the screen.',
        ],
        [
            'slug' => 'mirror-self-insert',
            'title' => 'Mirror Self-Insert',
            'one' => 'You are both the roast and the roasted.',
            'soft' => 'Soft: recognition heals.',
            'mirror' => 'Mirror: victim log has your handwriting.',
        ],
    ];
}

function kcj_content_glossary() {
    return [
        'chaebol' => 'Large family-controlled conglomerate culture often used as romance scaffolding in Korean stories.',
        'sageuk' => 'Korean historical drama setting; fusion sageuk mixes modern tone or fantasy into period dress.',
        'makjang' => 'Heightened melodrama mode — secrets, revenge, volume turned up.',
        'noona' => 'Korean address for older woman; as romance texture it signals care + age dynamics.',
        'sunbae' => 'Senior at work or school; hierarchy flavor in romance.',
        'xianxia' => 'Chinese fantasy cultivation romance worlds — destiny, sects, immortality politics.',
        'wuxia' => 'Martial-chivalry tradition; romance under codes of honor.',
        'danmei' => 'Chinese genre centered on romance between men; discuss as literacy, never pirate text.',
        'face-slapping' => 'Public status reversal / humiliation of a bully — catharsis engine.',
        'transmigration' => 'Waking into another body/story with prior knowledge.',
        'shokuba' => 'Japanese workplace drama setting.',
        'dorama' => 'Japanese TV drama; often shorter and quieter than K-drama rom-coms.',
        'tsundere' => 'Harsh-then-soft affection style — more anime-coded, echoes in some J romance.',
        'en' => 'Japanese idea of fateful connection; cousin to red-thread thinking.',
        'OST' => 'Original soundtrack; in K-romance especially, emotional architecture.',
        'second-lead' => 'The love interest who isn’t chosen — sometimes the audience favorite.',
        'contract-relationship' => 'Fake or paper bond used to unlock real intimacy plots.',
        'reincarnation-arc' => 'Second life used to correct regret and rediscover love.',
        'palace-intrigue' => 'Succession and surveillance as romance climate.',
        'slow-burn' => 'Delay as craft — intimacy earned by attention.',
    ];
}
